### ISSUE TITLE
trying to run retrogram on adalm pluto but missing a component.

### ISSUE THREAD

**Issue by glangsto** [r4d10n/retrogram-plutosdr#1]
hello

Thanks for your great effort in getting retrogram working.   It is working fine on my ODROID XU4 talking
to my adalm pluto.

Unfortunatelly, It is not running on my adalm pluto directly.   I've tried this several times.  I've also
updated to the latest pluto.frm version v0.29

I just swiped our commands and pasted into the command line on the pluto:
______ _       _        _________________
| ___ \ |     | |      /  ___|  _  \ ___ \
| |_/ / |_   _| |_ ___ \ `--.| | | | |_/ /
|  __/| | | | | __/ _ \ `--. \ | | |    /
| |   | | |_| | || (_) /\__/ / |/ /| |\ \
\_|   |_|\__,_|\__\___/\____/|___/ \_| \_|

v0.29
http://wiki.analog.com/university/tools/pluto
# ls /tmp
avahi-autoipd           fw_printenv.lock        messages                subsys
dbus                    linux                   retrogram-plutosdr.arm  udhcpd.leases
# cd /tmp
# mkdir /usr/share/terminfo
# mkdir /usr/share/terminfo/l
# cp linux /usr/share/terminfo/l
# export TERM=linux
# chmod +x ./retrogram-plutosdr.arm
# ./retrogram-plutosdr.arm --rate 61e6 --bw 56e6 --gain 73 --freq 935e6 --step 5e6
-sh: ./retrogram-plutosdr.arm: not found

So I think I;m missing a component.

Suggestions?

Thanks and happy new year.

Best regards
Glen

**Comment by r4d10n** [comment]
Can you try downloading the rerrogram-plutosdr.arm binary again? Pl paste output of 
ls -la /tmp
file /tmp/retrogram-plutosdr.arm

**Comment by unixpunk** [comment]
This is usually because the os and binary don't match exactly the arch.  i.e., if this worked on 0.28, but you're running 0.29, the key difference there is that .29 has switched over to hard float, eabi to eabihf, so its possible the binary needs to be recompiled accordingly.  Or maybe its vice-versa, just guessing.  On a side note, I'd like to include this in PlutoWeb, so I will be compiling it for .29 as well soon.  HTH

**Comment by unixpunk** [comment]
Try this one on 0.29, note the name is different: https://github.com/unixpunk/PlutoWeb/blob/master/plutoweb/overlay/bin/arm.retrogram-plutosdr Let me know.

**Comment by glangsto** [comment]
Hi Unixpunk,

Thanks for your suggestions for getting retrogram-plutosdr running
natively on my PlutoSDR.

I downloaded  your new executable and followed the instructions on the
github site.   Unfortunately I still get the same strange -sh message.

Below I summarize my steps, following your instructions:

Any further suggestions?

Thanks

Glen

odroid@odroid:~/Downloads$ cat retrogram-pluto.notes
On my odroid XU4  clicked on your link and downloaded your
new executable.
----------------------------------------------------
odroid@odroid:~/Downloads$ ls -l arm*
-rw-rw-r-- 1 odroid odroid 968112 Jan  7 08:33 arm.retrogram-plutosdr

scp arm.retrogram-plutosdr root@pluto.local:/tmp

wget https://github.com/r4d10n/retrogram-plutosdr/raw/master/linux
scp linux root@pluto.local:/tmp

-----------------------------------------------------
now on PlutoSDR
-----------------------------------------------------

ssh root@192.168.2.1's password:
Welcome to:
______ _       _        _________________
| ___ \ |     | |      /  ___|  _  \ ___ \
| |_/ / |_   _| |_ ___ \ `--.| | | | |_/ /
|  __/| | | | | __/ _ \ `--. \ | | |    /
| |   | | |_| | || (_) /\__/ / |/ /| |\ \
\_|   |_|\__,_|\__\___/\____/|___/ \_| \_|

v0.29
http://wiki.analog.com/university/tools/pluto
# cd /tmp
# mkdir /usr/share/terminfo
# mkdir /usr/share/terminfo/l
# cp linux /usr/share/terminfo/l
# export TERM=linux
# chmod +x ./arm.retrogram-plutosdr
# ./arm.retrogram-plutosdr --rate 61e6 --bw 56e6 --gain 73 --freq 935e6
--step 5e6
-sh: ./arm.retrogram-plutosdr: not found
# export PATH=./:$PATH
./:/bin:/sbin:/usr/bin:/usr/sbin
# ./arm.retrogram-plutosdr --rate 61e6 --bw 56e6 --gain 73 --freq 935e6
--step 5e6
-sh: ./arm.retrogram-plutosdr: not found

**Comment by unixpunk** [comment]
Seems still a hw/sw float mismatch.  What do you see from running this on your pluto?  ls -lah /usr/lib/ld-linux*

If you don't see /usr/lib/ld-linux-armhf.so.3 (the hf on the end is the important part) then this won't work.  You'd need a soft float version, which would be a version that should work on .28.  My version is hard float.  So what I'm getting at is, either the version that works on .28 will work for you OR my version should.  One or the other SHOULD work.

I will be releasing a new version of PlutoWeb and it will have this on there and working already, in case you want to wait for that.  Will only be a day or two at most.

HTH

Also, to be clear, I'm not ignoring the 'not found' error, I just know this is what happens when there's an arch mismatch, that's all.

**Comment by glangsto** [comment]
Hi Unixpunk,

Thanks again for looking into this.   I'm afraid I'm still learning my way around the PlutoSDR.

Strangely I'm also having some trouble going back a version.  I seem to only be able to access versions containing v0.29.  I'm still sorting this out.   

In any case, in v0.29 there is no /usr/lib/ld-linux-armhf.so.3
Here's what I find:
#  ls -lah /usr/lib/
total 4060
drwxr-xr-x    3 root     root           0 Aug 20  2018 .
drwxr-xr-x    7 root     root           0 Aug 20  2018 ..
drwxr-xr-x    2 root     root           0 Aug 20  2018 avahi
lrwxrwxrwx    1 root     root          14 Aug 20  2018 libad9361.so -> libad9361.so.0
lrwxrwxrwx    1 root     root          16 Aug 20  2018 libad9361.so.0 -> libad9361.so.0.1
-rwxr-xr-x    1 root     root        7.7K Aug 20  2018 libad9361.so.0.1
lrwxrwxrwx    1 root     root          15 Aug 20  2018 libaio.so -> libaio.so.1.0.1
lrwxrwxrwx    1 root     root          15 Aug 20  2018 libaio.so.1 -> libaio.so.1.0.1
-rwxr-xr-x    1 root     root        2.3K Aug 20  2018 libaio.so.1.0.1
lrwxrwxrwx    1 root     root          18 Aug 20  2018 libatomic.so.1 -> libatomic.so.1.1.0
-rwxr-xr-x    1 root     root       14.7K Aug 20  2018 libatomic.so.1.1.0
lrwxrwxrwx    1 root     root          24 Aug 20  2018 libavahi-client.so -> libavahi-client.so.3.2.9
lrwxrwxrwx    1 root     root          24 Aug 20  2018 libavahi-client.so.3 -> libavahi-client.so.3.2.9
-rwxr-xr-x    1 root     root       51.9K Aug 20  2018 libavahi-client.so.3.2.9
lrwxrwxrwx    1 root     root          24 Aug 20  2018 libavahi-common.so -> libavahi-common.so.3.5.3
lrwxrwxrwx    1 root     root          24 Aug 20  2018 libavahi-common.so.3 -> libavahi-common.so.3.5.3
-rwxr-xr-x    1 root     root       38.1K Aug 20  2018 libavahi-common.so.3.5.3
lrwxrwxrwx    1 root     root          22 Aug 20  2018 libavahi-core.so -> libavahi-core.so.7.0.2
lrwxrwxrwx    1 root     root          22 Aug 20  2018 libavahi-core.so.7 -> libavahi-core.so.7.0.2
-rwxr-xr-x    1 root     root      172.7K Aug 20  2018 libavahi-core.so.7.0.2
lrwxrwxrwx    1 root     root          18 Aug 20  2018 libdaemon.so -> libdaemon.so.0.5.0
lrwxrwxrwx    1 root     root          18 Aug 20  2018 libdaemon.so.0 -> libdaemon.so.0.5.0
-rwxr-xr-x    1 root     root       17.9K Aug 20  2018 libdaemon.so.0.5.0
lrwxrwxrwx    1 root     root          19 Aug 20  2018 libdbus-1.so -> libdbus-1.so.3.19.4
lrwxrwxrwx    1 root     root          19 Aug 20  2018 libdbus-1.so.3 -> libdbus-1.so.3.19.4
-rwxr-xr-x    1 root     root      228.2K Aug 20  2018 libdbus-1.so.3.19.4
lrwxrwxrwx    1 root     root          18 Aug 20  2018 libdns_sd.so -> libdns_sd.so.1.0.0
lrwxrwxrwx    1 root     root          18 Aug 20  2018 libdns_sd.so.1 -> libdns_sd.so.1.0.0
-rwxr-xr-x    1 root     root       26.0K Aug 20  2018 libdns_sd.so.1.0.0
lrwxrwxrwx    1 root     root          17 Aug 20  2018 libexpat.so -> libexpat.so.1.6.7
lrwxrwxrwx    1 root     root          17 Aug 20  2018 libexpat.so.1 -> libexpat.so.1.6.7
-rwxr-xr-x    1 root     root      108.0K Aug 20  2018 libexpat.so.1.6.7
lrwxrwxrwx    1 root     root          17 Aug 20  2018 libfftw3.so -> libfftw3.so.3.5.7
lrwxrwxrwx    1 root     root          17 Aug 20  2018 libfftw3.so.3 -> libfftw3.so.3.5.7
-rwxr-xr-x    1 root     root      610.6K Aug 20  2018 libfftw3.so.3.5.7
lrwxrwxrwx    1 root     root          11 Aug 20  2018 libiio.so -> libiio.so.0
lrwxrwxrwx    1 root     root          14 Aug 20  2018 libiio.so.0 -> libiio.so.0.15
-rwxr-xr-x    1 root     root       75.1K Aug 20  2018 libiio.so.0.15
lrwxrwxrwx    1 root     root          11 Aug 20  2018 libini.so -> libini.so.0
lrwxrwxrwx    1 root     root          13 Aug 20  2018 libini.so.0 -> libini.so.0.1
-rwxr-xr-x    1 root     root        5.6K Aug 20  2018 libini.so.0.1
lrwxrwxrwx    1 root     root          19 Aug 20  2018 libnl-3.so -> libnl-3.so.200.26.0
lrwxrwxrwx    1 root     root          19 Aug 20  2018 libnl-3.so.200 -> libnl-3.so.200.26.0
-rwxr-xr-x    1 root     root       95.0K Aug 20  2018 libnl-3.so.200.26.0
lrwxrwxrwx    1 root     root          24 Aug 20  2018 libnl-genl-3.so -> libnl-genl-3.so.200.26.0
lrwxrwxrwx    1 root     root          24 Aug 20  2018 libnl-genl-3.so.200 -> libnl-genl-3.so.200.26.0
-rwxr-xr-x    1 root     root       15.6K Aug 20  2018 libnl-genl-3.so.200.26.0
lrwxrwxrwx    1 root     root          25 Aug 20  2018 libnl-idiag-3.so -> libnl-idiag-3.so.200.26.0
lrwxrwxrwx    1 root     root          25 Aug 20  2018 libnl-idiag-3.so.200 -> libnl-idiag-3.so.200.26.0
-rwxr-xr-x    1 root     root       25.1K Aug 20  2018 libnl-idiag-3.so.200.26.0
lrwxrwxrwx    1 root     root          22 Aug 20  2018 libnl-nf-3.so -> libnl-nf-3.so.200.26.0
lrwxrwxrwx    1 root     root          22 Aug 20  2018 libnl-nf-3.so.200 -> libnl-nf-3.so.200.26.0
-rwxr-xr-x    1 root     root       67.5K Aug 20  2018 libnl-nf-3.so.200.26.0
lrwxrwxrwx    1 root     root          25 Aug 20  2018 libnl-route-3.so -> libnl-route-3.so.200.26.0
lrwxrwxrwx    1 root     root          25 Aug 20  2018 libnl-route-3.so.200 -> libnl-route-3.so.200.26.0
-rwxr-xr-x    1 root     root      351.1K Aug 20  2018 libnl-route-3.so.200.26.0
lrwxrwxrwx    1 root     root          24 Aug 20  2018 libnl-xfrm-3.so -> libnl-xfrm-3.so.200.26.0
lrwxrwxrwx    1 root     root          24 Aug 20  2018 libnl-xfrm-3.so.200 -> libnl-xfrm-3.so.200.26.0
-rwxr-xr-x    1 root     root       60.7K Aug 20  2018 libnl-xfrm-3.so.200.26.0
lrwxrwxrwx    1 root     root          22 Aug 20  2018 libserialport.so -> libserialport.so.0.1.0
lrwxrwxrwx    1 root     root          22 Aug 20  2018 libserialport.so.0 -> libserialport.so.0.1.0
-rwxr-xr-x    1 root     root       56.6K Aug 20  2018 libserialport.so.0.1.0
lrwxrwxrwx    1 root     root          19 Aug 20  2018 libstdc++.so.6 -> libstdc++.so.6.0.20
-rwxr-xr-x    1 root     root      790.2K Aug 20  2018 libstdc++.so.6.0.20
lrwxrwxrwx    1 root     root          19 Aug 20  2018 libusb-1.0.so -> libusb-1.0.so.0.1.0
lrwxrwxrwx    1 root     root          19 Aug 20  2018 libusb-1.0.so.0 -> libusb-1.0.so.0.1.0
-rwxr-xr-x    1 root     root       74.5K Aug 20  2018 libusb-1.0.so.0.1.0
lrwxrwxrwx    1 root     root          16 Aug 20  2018 libxml2.so -> libxml2.so.2.9.7
lrwxrwxrwx    1 root     root          16 Aug 20  2018 libxml2.so.2 -> libxml2.so.2.9.7
-rwxr-xr-x    1 root     root        1.0M Aug 20  2018 libxml2.so.2.9.7
lrwxrwxrwx    1 root     root          14 Aug 20  2018 libz.so -> libz.so.1.2.11
lrwxrwxrwx    1 root     root          14 Aug 20  2018 libz.so.1 -> libz.so.1.2.11
-rwxr-xr-x    1 root     root       70.6K Aug 20  2018 libz.so.1.2.11
-rw-r--r--    1 root     root         116 Aug 20  2018 os-release
-rw-r--r--    1 root     root         315 Aug 20  2018 xml2Conf.sh
