### ISSUE TITLE
std::out_of_range

### ISSUE THREAD

**Issue by alphafox02** [r4d10n/retrogram-plutosdr#3]
Thank you for update, not sure if this is just an issue specific to me or not. Thought I'd share and provide some feedback.

Hardware:
PlutoSDR with firmware v33

Steps to reproduce:

Installed latest retrogram-plutosdr according to steps listed
Starting up the program and let it run for roughly 5-10 minutes (Appears to run fine with no errors)

Without touching anything the following eventually shows up:

Terminate called after throwing an instance of 'std::out_of_range'
what():  basic_string::at: __n (which is 4) >= this->size() (which is 4)
Aborted

**Comment by r4d10n** [comment]
Thanks for the check... I did notice this once or twice. 

It seems @mbr0wn had fixed it in the UHD repo sometime ago - commit https://github.com/EttusResearch/uhd/commit/33233e5c77f495a54d21bd949ea9c7d3a9634e87 .

It has been running fine here for a while now. Let me know if its okay.

**Comment by alphafox02** [comment]
Hmm, rebuilt firmware. I run it and at about 5-6mins or so, maybe longer, it’ll stop with that error on the screen. Besides that, it does seem like all the functions work really smooth.

**Comment by alphafox02** [comment]
If it helps any, I noticed after that happens if I type clear the screen clears. However, the next command I type to spit out say -help on something, the resulting print is spread across to the right and sort of downward as it goes, if that makes sense. Unable to provide screen shots at the moment. 

If I log out of the Pluto and back in, all is normal as far as what prints to the screen.

**Comment by r4d10n** [comment]
That's strange. 

Another hack I tried earlier was to surround the plot commands with empty try-catch. Could you try this and let me know ? 
https://github.com/r4d10n/retrogram-plutosdr/blob/c60cece424d097b7fef40d62522bbc686f273b16/retrogram-plutosdr.cpp#L289 

```
try 
{
  std::string frame = ascii_art_dft::dft_to_plot(
              lpdft, COLS, (show_controls ? LINES-5 : LINES),
              rate,
              freq,
              dyn_rng, ref_lvl
          );
}
catch(...){}

```
The second part you have mentioned is due to terminal not being reset due to execution abortion.

**Comment by alphafox02** [comment]
Sure will, but make take me awhile to get it built from source. I used your .arm that was already built. Might try and use buildroot or cross compile on the pi over the weekend.

**Comment by r4d10n** [comment]
I have just updated the repo with the suggested fix and the ARM binary as well. Let me know how it goes.

**Comment by alphafox02** [comment]
Excellent, I’ll be able to try first thing tomorrow. Thank you!

**Comment by alphafox02** [comment]
Happy to report that so far I’ve reached twenty minutes continuous running of the application and it’s still going. This was not possible for me before. I’ll keep trying and also letting it run and if no issues i think it would be safe to say it’s resolved. Thank you!

**Comment by alphafox02** [comment]
I’ve now ran it multiple times and the latest time is almost at an hour. I’m unable to reproduce the initial issue. I believe it’s fixed, at least in my case with it running on a PlutoSDR revC
